### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/powershell#155]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total...........28
✅ Successful......22
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........6

Errors in ./README.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/dd878238(v=vs.85).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/dd878238(v=vs.85).aspx))</span>
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/dd878291(v=vs.85).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/dd878291(v=vs.85).aspx))</span>
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/ms714657(v=vs.85).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/ms714657(v=vs.85).aspx))</span>
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx))</span>
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx))</span>

Errors in ./docs/LEARNING.md
<span style="color:#ff5555">✗ https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/?view=powershell-6 (error following redirect for url (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about?view=powershell-6): too many redirects)</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by hkbertoson** [comment]
Opened #178 for this.
