### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/powershell#156]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/powershell/runs/3066725013
https://github.com/exercism/powershell/runs/3066724959
https://github.com/exercism/powershell/runs/3066724837

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by KalebHawkins** [comment]
Working on this not sure how to claim it as in-progress.

**Comment by glennj** [comment]
> Working on this not sure how to claim it as in-progress.

You can assign it to yourself.

**Comment by ErikSchierboom** [comment]
@glennj I don't think @KalebHawkins has the permissions to do that. I've done it for you.

**Comment by KalebHawkins** [comment]
@ErikSchierboom  Thanks!
