### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/powershell#2]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

---

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by kchenery** [comment]
@kytrinyx does the `SETUP.md` file need to be in the `docs` directory?  I've assumed it does and have a PR open (#40 Adding required docs) that would satisfy this issue I believe.

**Comment by kytrinyx** [comment]
@kchenery Ah, shoot. We changed how the READMEs get generated. It's documented here: https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

If that's confusing let me know and I'll take a stab at clarifying.

The TL;DR is that the track has a template for the readmes in `config/exercise_readme.go.tmpl`, but if you need to, you can override that template for a single exercise. If you don't override the generic template, then you don't need to worry about an extra file for shared README contents (you can just stick it in the generic template).

**Comment by kchenery** [comment]
All good - still learning how we hang this all together!

I had read through that document and have seen how `configlet` pulls the information from the `problem-specifications`.  I guess I was a little confused as I had seen the `SETUP.md` somewhere.  Am I correct in understanding we just need to put together the readme spec as per that document and that is all?

In the simplest example there'd be nothing to add right...we'd just take the default information from the generic specification?  In more complex or esoteric examples we might want to add language specific information and would use that Go spec to put our own descriptions in?

If thats the case, I think we can just close this PR and I can go fix up the two exercises we do have.

**Comment by kytrinyx** [comment]
> I guess I was a little confused as I had seen the SETUP.md somewhere.

I wouldn't be surprised if you had seen the `SETUP.md` somewhere. I've tried to clean it all out, but may well have missed a spot.

> Am I correct in understanding we just need to put together the readme spec as per that document and that is all?

Yepp, and there's one in the repo which *should* do the right thing, and which you could tweak to your heart's content.



> If thats the case, I think we can just close this PR and I can go fix up the two exercises we do have.

Awesome, yeah. I think that's the next step, then. 🌷

**Comment by kchenery** [comment]
Probably saw it here! 😄

**Comment by kchenery** [comment]
Please close this issue as its now redundant (see discussion).
