### ISSUE TITLE
Hello World exercise instructions are confusing and conflicting

### ISSUE THREAD

**Issue by kchenery** [exercism/powershell#36]
Following the instructions for the Hello World exercise exactly does not guide the user accurately.  The tests still fail and there is some confusion around the naming of files.

**Comment by Tuxhedoh** [comment]
I'm trying to work through this first exercise. Is the only way for us to test to use a function?  It would seem that building functions is a more advanced exercise.

**Comment by kchenery** [comment]
I can think of 3 ways you can write PowerShell...

I'll use the Hello, World! example to demonstrate.

### 1. Inline
``` PowerShell
PS> "Hello, World!"
```
or if you were to be more accurate:
``` PowerShell
PS> Write-Output "Hello, World!"
```

That would actually output what is needed to pass the first test.  Clearly we can't test that and it's not going to accept parameters.  However; there are times you'll do this in the real world.

#### 2. Function
``` PowerShell
Function HelloWorld {
    Write-Output "Hello, World"
}
```
And then you can call that function.  The __big__ advantage here is that we can test this.  It seems to me that one of the goals of `exercise.io` is to encourage test driven development.  I don't know this to be 100% true, its just an observation.

#### 3. Script
We could have a HelloWorld.ps1 file that contains:
``` PowerShell
Write-Output "Hello, World"
```
This would work too.  You can even have scripts take parameters and the lines between a script and a function start to become very blurred!  You can `.` source a script file to load it and PowerShell also uses `&` to run a command.  I am not sure if the `Pester` framework could test this approach (I may test this for my own benefit).  

The authors of PowerShell have been quite firm on best practices and standards for PowerShell.  And one of those best practices is to create functions and modules rather than scripts.  They are wanting you to think about writing reusable pieces of code rather than one offs.

I think we should be encouraging the same approaches and practices that you will find elsewhere (especially in the industry).

**Comment by ErikSchierboom** [comment]
> The authors of PowerShell have been quite firm on best practices and standards for PowerShell. And one of those best practices is to create functions and modules rather than scripts. They are wanting you to think about writing reusable pieces of code rather than one offs.
>
> I think we should be encouraging the same approaches and practices that you will find elsewhere (especially in the industry).

I agree with this sentiment. If we look at the [stub of the `hello-world` exercise](https://github.com/exercism/powershell/blob/master/exercises/hello-world/HelloWorld.ps1), that looks quite nice to me. @kchenery what do you think of the stub now?
