### ISSUE TITLE
Missing ABOUT.md

### ISSUE THREAD

**Issue by kchenery** [exercism/powershell#38]
When you browse to the [about PowerShell section on exercise.io](http://exercism.io/languages/powershell/about) the "complains" that `about.md` is missing.  We should add this file to describe the language.

**Comment by gyssels** [comment]
http://exercism.io/languages/powershell/about

continues to complain... even after commit

**Comment by gyssels** [comment]
Published to "http://exercism.io/languages/powershell/about"
