### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/powershell#4]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

If you are interested in leading the charge on getting this track launched, then comment below, and I'll help get this party started based on whatever is current at the time.

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by trebleCode** [comment]
@kytrinyx are you still looking for people to help out with this track?
I would love to help with this!

**Comment by kchenery** [comment]
I was going to suggest exercism.io to my team to learn some PowerShell but was disappointed to find only two exercises.  I'm keen to help build this out.  Would be keen to discuss how I can help!

I realise I can submit pull requests to add exercises.  I think there's more than can be offered. Or would the preference be to just be to submit the PRs for new exercises?

**Comment by kytrinyx** [comment]
> are you still looking for people to help out with this track?
> I would love to help with this!

@trebleCode Yes! Holy moly yes please ✨ 

@kchenery @trebleCode I would be happy to give you both commit access / maintainership on this repository. I've got a bunch of documentation on how to get a track up and running here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md (this further links to a bunch of documents).

Also, you're welcome to ask questions along the way. I'll see if we have a couple of existing maintainers who would be willing to be on call for questions from you as well.

So, step one: do you want to be a maintainer on this track? If so, say the word and I will make it so!

**Comment by Tuxhedoh** [comment]
I'd be happy to assist, though, I'm not sure how I might help.

**Comment by kytrinyx** [comment]
@Tuxhedoh - the first step would be to read through the launch guide: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

The basics are:

- implement exercises
- help write scripts so we can run the exercise tests on CI
- watch the repository and respond and help answer questions and review pull requests when there is activity in the repository

After reading through the launch guide, if this sounds like something you're interested in, let me know and I'll add you to the team.

**Comment by trebleCode** [comment]
@kytrinix

Are your CI tests for this intended to be done through the Pester framework for PS, or do you do C# unit tests or otherwise?

**Comment by trebleCode** [comment]
And yes I'd be happy to help maintain this track. Been itching for a software project to contribute to

**Comment by kytrinyx** [comment]
> Are your CI tests for this intended to be done through the Pester framework for PS, or do you do C# unit tests or otherwise?

I don't actually know what the thinking was for the CI tests. My best advice here would be for the three of you to discuss what you think would be a good choice for CI.

Here's what I wrote up about what we're trying to achieve: https://github.com/exercism/docs/blob/a8ea5db92e2a2d2839e66ec10c7687b3b7db002a/language-tracks/launch/tooling-and-ci.md#tooling-and-continuous-integration

I've added you as a maintainer to this repo. 🎈 🎈 welcome 🎈 🎈

**Comment by kchenery** [comment]
Im certainly keen to get this kicked off.  @Tuxhedoh and @trebleCode how do you want to catch up?

Regarding the CI tests, I'd favour Pester for the following reasons:
* Its the standard PowerShell testing framework
* Its (now) installed by default
* Its easy to pick up/learn

**Comment by kytrinyx** [comment]
From the peanut gallery... :)

> * Its the standard PowerShell testing framework
> * Its (now) installed by default

Those two arguments are some of my favorite. Easy to pick up/learn is a great bonus :)

**Comment by trebleCode** [comment]
Pester seems like the best outta-the-box solution and agree that it's easy
to pick up. So what are thinking? Divy up the first few exercises and
provide a Pester script with each one?

**Comment by Tuxhedoh** [comment]
I've had problems getting the exercism to work for some reason. There are 2
exercises for Powershell available, but I can't figure out how to test my
solution. I can't figure out whether the documentation for getting it setup
is incorrect or not. Perhaps we should start there. :D Get it working for
me! :D

Otherwise, I have no reason  to want to use another testing framework.

**Comment by kchenery** [comment]
Yeah...I've just followed the instructions word for word and they're not good.  I'll fix this up!  Before I submit the PR it would be good to get a bit of a consensus on issue #15 to kick off how we should go on.

**Comment by trebleCode** [comment]
Let's use the HelloWorld.ps1 name convention since that's the Ms
recommended practice. Indifferent on EOL choice.

For these exercises does anyone forsee having to use #requires, and
presuming we are starting from PSv3 and up since 2 is now deprecated?

**Comment by kchenery** [comment]
I cant see a need for `#requires`.  Is there something you're specifically thinking of?  Just the PS version?  We could add that I guess...probably unnecessary though.

**Comment by trebleCode** [comment]
Not at the moment, just one of many considerations before we started
writing exercises

**Comment by kchenery** [comment]
@trebleCode I believe I've tidied up the confusion in the Hello World exercise with this PR #37 

Although I need to tidy up the config for exercism (according to the build failure)

**Comment by kchenery** [comment]
Sorted the config (I believe...TravisCI is now passing at least!).  Keen to understand if this updated HelloWorld is the approach we want.  I have a couple of other exercises (leap and twofer) ready to add if it is.

**Comment by Jaykul** [comment]
Hey, I'd also be interested in helping get this off the ground ... I'll poke around a bit this evening.

Can we strike the word "Windows" from **everything** and just call it "PowerShell"? Of course the examples should all work on the old Windows PowerShell releases (after all, you're teaching language, not cmdlets) but the focus should be on the current, open-source, cross-platform PowerShell Core (aka PowerShell 6), not the old "Windows PowerShell."

**Comment by kchenery** [comment]
Not until PowerShell Core is released. Its technically still Windows PowerShell for now.

**Comment by JPRuskin** [comment]
Also here to help, if needed, and will be exploring shortly.

**Comment by gyssels** [comment]
@JPRuskin @kchenery @trebleCode @Jaykul @Tuxhedoh @spuder @inammathe @andrewiiird @catb0t 
@cgrayson @iHiD @dkinzer @eemailme @davzoku

Call to arms! Choose your exercise!

#44 #45 #46 #50 #56 #57 #58 #59 - Witch exercise will you pick? Please assign the issue to your login!

**Comment by gyssels** [comment]
**Exercises (1-20) - Implementation/Track order #47** has a list of opened exercise request with the issue number _you can choose from_

**Comment by kchenery** [comment]
@gyssels dont seem to be able to assign myself some issues.  I was going to go work on Exercise 4 (Bob).  Issue #44

**Comment by gyssels** [comment]
Katrina Owen, It's seems rights management. I can't assign him neither. Can you have a look?

thank you,
Christian




______________________________________________________
Christian P. Gyssels

www.dekeract.com<http://www.dekeract.com>

Brazil | Belgium | Germany | France | United Kingdom

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments,is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

________________________________

**Comment by kytrinyx** [comment]
@gyssels - GitHub organizations will only allow people to be assigned if they are members of the org.

For the moment, would you all manage this by adding comments to the individual issues? I don't have the bandwidth this week to handle this.

**Comment by devblackops** [comment]
I'm interested in helping out with this project as well.

**Comment by trebleCode** [comment]
@kytrinyx what issues on here are currently open? Would like to knock out a couple if available

**Comment by kytrinyx** [comment]
@trebleCode I actually have no idea what the status of this one is, and would be super grateful for some help figuring out what's going on, and what would be next steps.

From a quick survey it looks like:

- the track has not officially launched on the site (it's not on the homepage on https://exercism.io)
- the track *is* available to play around with (https://exercism.io/tracks/powershell)
- there's one person signed up to provide feedback on the track
- there are 9 available exercises
- there are 150+ people who have tried it out

There are two parts to getting the track ready for launch

1. "getting started" documentation
2. exercises

The most important thing about the exercises to start off with are that:

- the first core exercise should be hello-world
- hello world is as simple as it gets, per: https://github.com/exercism/exercism/issues/4707
- the second core exercise should be "two-fer"
- both hello world and two fer should unlock 2 or 3 side exercises each

In terms of which exercises to implement, I'd recommend looking at the Ruby or C# tracks to look at which exercises they've put as core and side. This will not be a perfect match for PowerShell because (obviously) the languages are different, but in the absence of having actually done any analysis regarding which features of PowerShell should be covered, etc, it's probably a pretty decent guess.

I think it's more important to have 10 good exercises in a good order than to have 80 exercise in a haphazard order!

It's also going to be important that we find a handful of people who are interested in mentoring on the site once the track goes live, and if possible, that they actively discuss with each other in the exercism-team Slack workspace (#track-powershell channel). That way we would start getting an understanding of what typical mistakes people make, what's hard, what's easy, and what's missing.

Is this helpful?

**Comment by inammathe** [comment]
One more for 10! #59 is good one, I've got #100 opened for it - Would love to see some more action on that one ;)

I would be keen to be a mentor/maintainer :grinning:

Thanks for the comment @kytrinyx, I'll have to hop on #track-powershell!

**Comment by kytrinyx** [comment]
@inammathe invite incoming! I've found that when we have three people active as track maintainers at once, magical things happen. It turns out, it's _really_ helpful to be able to think out loud about things, and throw ideas back and forth.

**Comment by tqa236** [comment]
Hello, do you plan when you will launch this track? I would love to try it out.

**Comment by ErikSchierboom** [comment]
@Hanimn This is a really useful issue to keep open, as it contains a link to the [launch checklist](https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md).
