### ISSUE TITLE
Exercise 4 - Bob

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#44]
First: thank you for your help!
Request specifications:

Please work from the  **Exercise-4-Bob** branch.

Bob exercism files to implement:
- **.\exercises\bob\BobResponse.tests.ps1** as specified in https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json
- **.\exercises\bob\BobResponse.example.ps1**, your solution as specified in .\exercises\bob\README.md
- **.\exercises\bob\BobResponse.ps1**, with function with right signature with Not Implemented exception for the user can work with

_Do not touch_, as it will not be merged:
.\config.json
.\exercises\bob\README.md

**Comment by gyssels** [comment]
Created a new **Exercise-4-Bob** branch for working with this exercise.

**Comment by kchenery** [comment]
Wanted to assign this to myself @gyssels, however I am unable to do so.

**Comment by gyssels** [comment]
All right. Published...
