### ISSUE TITLE
Exercise 5 - Sum-Of-Multiples

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#45]
First: thank you for your help!
Request specifications:

Please work from the **Exercise-5-SumOfMmultiples** branch.

Sum-Of-Multiples exercism files to implement:

- **.\exercises\sum-of-multiples\SumOfMultiples.tests.ps1** as specified in https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json
- **.\exercises\sum-of-multiples\SumOfMultiples.example.ps1**, your solution as specified in .\exercises\sum-of-multiples\README.md
- **.\exercises\sum-of-multiples\SumOfMultiples.ps1**, with function with right signature with Not Implemented exception for the user can work with

_Do not touch_, as it will not be merged:
.\config.json
.\exercises\sum-of-multiples\README.md

**Comment by gyssels** [comment]
Created a new **Exercise-5-SumOfMultiples** branch for working with this exercise.

**Comment by kchenery** [comment]
Dont think this has been picked up so will take a look.

**Comment by gyssels** [comment]
done
