### ISSUE TITLE
Exercises (1-20) - Implementation/Track order

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#47]
**FYI** - _Regarding the exercises implementation/track order_

As the F# and C# track are mature and have implemented all exercises, I made a choice to implement more or less at the same order, making adjustments as necessary. For now, the first 20 exercises:

1. "hello-world" [done]
2. "reverse-string", open issue #50
3. "leap" [done]
4. "bob", open issue #44 
5. "sum-of-multiples", open issue #45 
6. "raindrops", open issue #56
7. "two-fer" [done]
8. "nucleotide-count", open issue #57
9. "accumulate", open issue #58
10. "grade-school", open issue #59
11. "collatz-conjecture"
12. "armstrong-numbers"
13. "kindergarten-garden"
14. "clock"
15. "binary-search"
16. "allergies"
17. "saddle-points"
18. "markdown"
19. "book-store"
20. "gigasecond"
...
24 - "hamming" [done]

Of course not a decision _made in stone_.

If you have another point of view, please share!

**Comment by kchenery** [comment]
@gyssels  - I noticed you removed the [comment based help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-6) from my example solutions.  Fully appreciate its not a requirement to solve the problems functionally.

As this is a best practice, should we not be encouraging this?

**Comment by gyssels** [comment]
@kchenery you are right

**Comment by ErikSchierboom** [comment]
@Hanimn You can use this list of exercises for inspiration on which exercises to add. That said, this list is based on an older version of the C# track. The latest version uses different _core_ exercises and I'd highly suggest using the latest version. You can find the C# track's current core exercises by looking for the exercises in the https://github.com/exercism/csharp/blob/master/config.json file with `"core": true`.
