### ISSUE TITLE
Exercise 6 - Raindrops

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#56]
First: thank you for your help!
Request specifications:

Please work from the **Exercise-6-Raindrops branch**.

Raindrops exercism files to implement:

-**.\exercises\raindrops\Raindrops.tests.ps1** as specified in https://github.com/exercism/problem-specifications/blob/master/exercises/raindrops/canonical-data.json
-**.\exercises\raindrops\Raindrops.example.ps1**, your solution as specified in .\exercises\raindrops\README.md
-**.\exercises\raindrops\Raindrops.ps1**, a function with "Not implemented exception" for student play with it

Do not touch, as it will not be merged:
.\config.json
.\exercises\raindrops\README.md (Autogenerated)

**Comment by gyssels** [comment]
Created a new **Exercise-6-Raindrops** branch for working with this exercise.

**Comment by gyssels** [comment]
@kchenery  good! I will have a look about the commit errors by monday night. but seems the right logic! thankyou

**Comment by kchenery** [comment]
Seems to be issues around the config.json failing the checks which youve asked we dont touch.

**Comment by gyssels** [comment]
Yes. it was a config error on the first line. thank you.

**Comment by gyssels** [comment]
All right. Published...
