### ISSUE TITLE
Exercise 8 - NucleotideCount

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#57]
First: thank you for your help!
Request specifications:

Please work from the **Exercise-8-NucleotideCount** branch.

Bob exercism files to implement:
- **.\exercises\nucleotide-count\NucleotideCount.tests.ps1** as specified in https://github.com/exercism/problem-specifications/blob/master/exercises/nucleotide-count/canonical-data.json
- **.\exercises\nucleotide-count\NucleotideCount.example.ps1**, your solution as specified in .\exercises\nucleotide-count\README.md
- **.\exercises\nucleotide-count\NucleotideCount.ps1**,, a function with "Not implemented exception" for the user can play with it

_Do not touch_, as it will not be merged:
.\config.json
.\exercises\nucleotide-count\README.md (autogenerated)

**Comment by gyssels** [comment]
Created a new  **Exercise-8-NucleotideCount** branch for working with this exercise.

**Comment by kchenery** [comment]
Have created a PR (see above #67) to resolve this issue.

**Comment by gyssels** [comment]
All right. Published...
