### ISSUE TITLE
Exercise 10 - GradeSchool

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#59]
First: thank you for your help!
Request specifications:

Please work from the **Exercise-10-GradeSchool** branch.

Bob exercism files to implement:
- **.\exercises\grade-school\GradeSchool.tests.ps1** as specified in https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json
- **.\exercises\grade-school\GradeSchool.example.ps1**, your solution as specified in .\exercises\grade-school\README.md
- **.\exercises\grade-school\GradeSchool.ps1**, a function with "Not implemented exception" for the user can play with it.

_Do not touch_, as it will not be merged:
.\config.json
.\exercises\grade-school\README.md (autogenerated)

**Comment by gyssels** [comment]
Created a new **Exercise-10-GradeSchool** branch for working with this exercise.

**Comment by inammathe** [comment]
I'd be happy to help out on this one

**Comment by inammathe** [comment]
Wasn't entirely sure if that was the direction people want to go with this one (referring to https://github.com/exercism/powershell/pull/100).

I think it is a pretty good opportunity to introduce classes, however, it is possible to accomplish the same result without the use of classes (just writing  `[pscustomobject]` with the grade and name properties to output).

Happy to discuss here or within that PR.

**Comment by inammathe** [comment]
@gyssels :)
