### ISSUE TITLE
Finishing the code to auto-generate 98 exercises folders

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#65]
it's look like I didn't commit anything for days now, but as we feel alone I missed the oportunity to share the following and just wanted to say that I'm finishing and testing this 5 steps:

1. generation from  https://github.com/exercism/problem-specifications of the tests files for all exercises that have a canonical-data.json on it. (Around 98 exercises from the Exercism exercises base)
2. generating also the main config.json. and auto-updating with new exercises. 
3. generating the readme.md of  exercises( calling the configlet.exe from script)
4. generating a empty [exercisename].ps1 for the student.
5. a temporary  [exercisename].example.ps1 that pass the tests...

By publishing it I hope to accelerate the launch bu capturing the best examples from student for the example files, while they beta test the track.

**Comment by gyssels** [comment]
Refactoring it.

**Comment by masters3d** [comment]
Related to this conversation:
https://github.com/exercism/powershell/issues/79

**Comment by masters3d** [comment]
Can we break this down? Can you check in your current script that does this?

**Comment by ErikSchierboom** [comment]
@gyssels Do you still have the script somewhere that you were working? @Hanimn will be working on getting the Powershell track launched, and an auto-generate script could be extremely useful!

**Comment by kytrinyx** [comment]
@Hanimn @gyssels Are either of you planning on doing work on this track?

If so, please check in here: https://github.com/exercism/powershell/pull/179
