### ISSUE TITLE
"checklist_issue": 4 is giving a problem with Travis

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#69]
"checklist_issue": 4 is giving a problem. didn't find doc about this entry for config.json.

What it's related to? Can we remove it?

**Comment by gyssels** [comment]
not urgent, whenever you have time.

**Comment by kytrinyx** [comment]
The checklist issue number is used to link to it in http://exercism.io/languages/powershell/launch

I'll get this sorted in the next few days.

**Comment by kytrinyx** [comment]
@gyssels I downloaded the latest release of configlet and used it to reformat the configs (`configlet fmt .`) and I am not getting any errors.

What kind of problems are you seeing?

**Comment by gyssels** [comment]
I actually changed "checklist_issue": 4 to "checklist_issue": "4" manually, that's why you didn't fond anything. I saw that the previous configlet didn't pointed that as an issue;

**Comment by kytrinyx** [comment]
Someone pointed that out this morning /facepalm. I've updated configlet to expect an int, and will submit a fix here when I cut the release.

Sorry about the trouble!

**Comment by gyssels** [comment]
;)
